# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1esLuYoZ1lZU3NfRzDV-HQgdqC-jowp
"""

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st


st.set_page_config(
    page_title="EquiCure Research",
    page_icon="■",
    layout="wide",
    initial_sidebar_state="expanded",
)
st.title("EquiCure Research")
st.markdown("**Machine learning-based emergency department wait-time analysis in Los Angeles County.**")
st.divider()

# Build the CSV path relative to app.py, not the terminal location.
APP_DIR = Path(__file__).resolve().parent
DATA_PATH = APP_DIR / "assets" / "la_merged_dataset.csv"


@st.cache_data
def load_data(file_path: Path) -> pd.DataFrame:
    """Load and clean the LA County dataset."""
    data = pd.read_csv(file_path)

    if "Score" not in data.columns:
        raise ValueError(
            "The dataset does not contain a column named 'Score'."
        )

    data["Score"] = pd.to_numeric(data["Score"], errors="coerce")
    return data.dropna(subset=["Score"])


# Stop cleanly if the dataset cannot be found.
if not DATA_PATH.exists():
    st.error(f"Dataset not found: {DATA_PATH}")
    st.stop()

try:
    df = load_data(DATA_PATH)
except Exception as error:
    st.error(f"Could not load the dataset: {error}")
    st.stop()


# Header
st.title("EquiCure Research")
st.markdown("ML-based ED wait time disparity analysis — LA County.")
st.divider()


# Metrics
c1, c2, c3, c4, c5 = st.columns(5)

c1.metric("Facilities", "58")
c2.metric("Champion RMSE", "44.73 min")
c3.metric("CV-RMSE", "55.81 ± 10.02 min")
c4.metric("Models Tested", "14")
c5.metric("Median Wait", "202 min")

st.divider()

st.info(
    "Key Finding: Linear Regression outperformed all 14 models. "
    "RMSE = 44.73 minutes; CV-RMSE = 55.81 minutes."
)

st.subheader("Project Overview")

st.markdown("""
EquiCure studies whether public healthcare data can be used to estimate emergency department wait times
for Los Angeles County facilities. The project also evaluates whether model performance differs across
equity-relevant groups such as income level, payer mix, and facility type.
""")

# Model performance chart
st.subheader("Model Performance Overview")

models_df = pd.DataFrame(
    {
        "Model": [
            "Linear Regression",
            "SVR (RBF)",
            "Random Forest",
            "KNN (k=5)",
            "XGBoost",
            "LightGBM",
        ],
        "RMSE": [44.73, 49.46, 54.90, 55.33, 58.72, 64.55],
        "Champion": [True, False, False, False, False, False],
    }
)

fig = px.bar(
    models_df,
    x="Model",
    y="RMSE",
    color="Champion",
    color_discrete_map={
        True: "#2E7D32",
        False: "#1565C0",
    },
    title="Top 6 Models by RMSE (lower is better)",
)

fig.update_layout(
    showlegend=False,
    plot_bgcolor="white",
)

st.plotly_chart(fig, use_container_width=True)

st.subheader("Key Findings")

st.success("Linear Regression was the strongest baseline model with RMSE = 44.73 minutes and MAE = 39.28 minutes.")
st.info("More complex models such as Random Forest and XGBoost did not improve performance on the current dataset.")
st.warning("Results are preliminary because only 58 facilities had valid OP-18b scores after cleaning.")

# Dataset charts
st.subheader("Data at a Glance")

left, right = st.columns(2)

with left:
    fig2 = px.histogram(
        df,
        x="Score",
        nbins=20,
        color_discrete_sequence=["#1565C0"],
        title="Wait Time Distribution — LA County",
    )

    st.plotly_chart(fig2, use_container_width=True)


with right:
    if "Hospital Ownership" in df.columns:
        ownership_counts = (
            df["Hospital Ownership"]
            .fillna("Unknown")
            .value_counts()
            .rename_axis("Ownership")
            .reset_index(name="Count")
        )

        fig3 = px.pie(
            ownership_counts,
            names="Ownership",
            values="Count",
            title="Ownership Type Breakdown",
        )

        st.plotly_chart(fig3, use_container_width=True)

    else:
        st.warning(
            "The dataset does not contain a "
            "'Hospital Ownership' column."
        )
