# -*- coding: utf-8 -*-
"""1_Findings.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgVmVXeYZ3vgdM-75ueH6cCuh4oesCk2
"""

# pages/1_Findings.py

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

from style import apply_global_style, page_header, sidebar_summary, COLOR

st.set_page_config(
    page_title="Findings",
    page_icon="■",
    layout="wide",
)


# Find the main project directory.
# __file__ is pages/1_Findings.py, so parents[1] is the project root.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
ASSETS_DIR = PROJECT_ROOT / "assets"

SHAP_RANKING_PATH = ASSETS_DIR / "shap_feature_ranking.csv"
SHAP_BEESWARM_PATH = ASSETS_DIR / "shap_beeswarm.png"
SHAP_WATERFALL_PATH = ASSETS_DIR / "shap_waterfall.png"


@st.cache_data
def load_shap_ranking(file_path: Path) -> pd.DataFrame:
    """Load the SHAP feature-ranking table."""
    data = pd.read_csv(file_path)

    required_columns = {"Feature", "Mean |SHAP|"}
    missing_columns = required_columns - set(data.columns)

    if missing_columns:
        raise ValueError(
            "The SHAP ranking file is missing these columns: "
            + ", ".join(sorted(missing_columns))
        )

    data["Mean |SHAP|"] = pd.to_numeric(
        data["Mean |SHAP|"],
        errors="coerce",
    )

    return data.dropna(subset=["Feature", "Mean |SHAP|"])


st.title("Equity Findings")
st.markdown(
    "SHAP feature analysis · Subgroup error · Geographic disparity"
)
st.divider()

st.info(
    "Income quartile and ownership type are among the strongest "
    "predictors of wait time."
)


# SHAP feature-ranking chart
st.subheader("SHAP Feature Importance Ranking")

if not SHAP_RANKING_PATH.exists():
    st.error(
        "SHAP ranking file not found:\n\n"
        f"`{SHAP_RANKING_PATH}`"
    )
    st.stop()

try:
    ranked = load_shap_ranking(SHAP_RANKING_PATH)
except Exception as error:
    st.error(f"Could not load the SHAP ranking data: {error}")
    st.stop()

fig_rank = px.bar(
    ranked.head(12),
    x="Mean |SHAP|",
    y="Feature",
    orientation="h",
    title="Top 12 Features by Mean |SHAP|",
    color="Mean |SHAP|",
    color_continuous_scale="Blues",
)

fig_rank.update_layout(
    yaxis={"autorange": "reversed"},
    plot_bgcolor="white",
    coloraxis_showscale=False,
)

st.plotly_chart(fig_rank, use_container_width=True)


# SHAP images
left, right = st.columns(2)

with left:
    st.subheader("SHAP Beeswarm")

    if SHAP_BEESWARM_PATH.exists():
        st.image(
            str(SHAP_BEESWARM_PATH),
            use_container_width=True,
        )
    else:
        st.warning(
            f"Image not found: `{SHAP_BEESWARM_PATH.name}`"
        )


with right:
    st.subheader("SHAP Waterfall")

    if SHAP_WATERFALL_PATH.exists():
        st.image(
            str(SHAP_WATERFALL_PATH),
            use_container_width=True,
        )
    else:
        st.warning(
            f"Image not found: `{SHAP_WATERFALL_PATH.name}`"
        )


# Temporary subgroup data
st.subheader("Subgroup RMSE by Income Quartile")

sub_df = pd.DataFrame(
    {
        "Income Quartile": [
            "Q1 (Lowest)",
            "Q2",
            "Q3",
            "Q4 (Highest)",
        ],
        "RMSE": [
            52.3,
            48.7,
            41.2,
            38.9,
        ],
    }
)

overall_rmse = 44.73
threshold = overall_rmse * 1.15

sub_df["Flagged"] = sub_df["RMSE"] > threshold

fig_sub = px.bar(
    sub_df,
    x="Income Quartile",
    y="RMSE",
    color="Flagged",
    color_discrete_map={
        True: "#C62828",
        False: "#1565C0",
    },
    title="Subgroup RMSE — Red Indicates More Than 15% Above Overall RMSE",
)

fig_sub.add_hline(
    y=threshold,
    line_dash="dash",
    line_color="red",
    annotation_text=f"15% threshold: {threshold:.2f}",
    annotation_position="top left",
)

fig_sub.update_layout(
    plot_bgcolor="white",
    showlegend=False,
)

st.plotly_chart(fig_sub, use_container_width=True)

# st.caption(
#     "The subgroup RMSE values above are placeholders and should be "
#     "replaced with the final values from the equity analysis output."
# )
