# -*- coding: utf-8 -*-
"""2_Predict.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbRLRFxU52AIYH7kZtfGNoMQfCq6jFNN
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

from style import apply_global_style, page_header, sidebar_summary, COLOR

st.set_page_config(
    page_title="Predict Wait Time",
    page_icon="🤖",
    layout="wide"
)

apply_global_style()
sidebar_summary()

# ── Header ────────────────────────────────────────────────────────────────────
page_header(
    "ED Wait-Time Prediction",
    "Estimate facility-level median emergency department wait time using the champion baseline model."
)

m1, m2, m3 = st.columns(3)
m1.metric("Champion Model", "Linear Regression")
m2.metric("Test RMSE", "44.73 min")
m3.metric("LA County Median", "202 min")

st.info(
    "This tool is for research demonstration only. It estimates facility-level wait time and should not be used for individual patient care decisions."
)

# ── Load champion model (cached — only loads once) ────────────────────────────
@st.cache_resource
def load_model():
    return joblib.load("assets/champion_model.pkl")

model = load_model()
st.success("Champion model loaded: Linear Regression (RMSE = 44.73 min)")

# ── Input form ────────────────────────────────────────────────────────────────
st.subheader("Step 1 — Enter Facility Characteristics")

col1, col2 = st.columns(2)

with col1:
    st.markdown("**Socioeconomic Features**")

    income_quartile = st.select_slider(
        "Income Quartile of Facility ZIP Code",
        options=[1, 2, 3, 4],
        value=2,
        help="1 = lowest income area  |  4 = highest income area"
    )

    median_income = st.number_input(
        "Median Household Income of ZIP Code ($)",
        min_value=20000,
        max_value=200000,
        value=65000,
        step=1000,
        help="From Census ACS data. LA County range: ~$30k to ~$150k"
    )

    zip_code = st.number_input(
        "ZIP Code",
        min_value=90001,
        max_value=93599,
        value=90001,
        help="5-digit LA County ZIP code"
    )

with col2:
    st.markdown("**Facility Features**")

    ownership = st.selectbox(
        "Hospital Ownership Type",
        options=[
            "Voluntary non-profit - Private",
            "Government - Local",
            "Government - State",
            "Proprietary",
            "Voluntary non-profit - Church",
            "Voluntary non-profit - Other",
        ],
        help="Select the ownership category of the facility"
    )

    op18b_available = st.radio(
        "Is OP-18b wait time data available for this facility?",
        options=[0, 1],
        format_func=lambda x: "Yes — data available" if x == 0
                              else "No — data missing",
        horizontal=True
    )

    la_county = st.radio(
        "Is this an LA County facility?",
        options=[1, 0],
        format_func=lambda x: "Yes" if x == 1 else "No",
        horizontal=True
    )

st.divider()

# ── Build feature vector ──────────────────────────────────────────────────────
# This must match X_train.columns exactly
# Your columns: ['ZIP Code_x','op18b_missing','la_county_facility_match',
#                'ZIP Code_y','median_income','income_quartile',
#                'own_Government - Local','own_Government - State',
#                'own_Proprietary','own_Voluntary non-profit - Church',
#                'own_Voluntary non-profit - Other',
#                'own_Voluntary non-profit - Private']

def build_feature_vector(income_q, med_inc, own_type,
                          op18b_miss, la_match, zip_code):

    # All ownership columns start at 0
    ownership_cols = {
        "own_Government - Local":             0,
        "own_Government - State":             0,
        "own_Proprietary":                    0,
        "own_Voluntary non-profit - Church":  0,
        "own_Voluntary non-profit - Other":   0,
        "own_Voluntary non-profit - Private": 0,
    }

    # Set the selected ownership to 1
    key = f"own_{own_type}"
    if key in ownership_cols:
        ownership_cols[key] = 1

    # Build the full feature row
    row = {
        "ZIP Code_x":               zip_code,
        "op18b_missing":            op18b_miss,
        "la_county_facility_match": la_match,
        "ZIP Code_y":               zip_code,
        "median_income":            med_inc,
        "income_quartile":          income_q,
        **ownership_cols
    }

    return pd.DataFrame([row])

# ── Prediction button ─────────────────────────────────────────────────────────
st.subheader("Step 2 — Get Prediction")

if st.button("Predict Wait Time", type="primary",
             use_container_width=True):

    # Build feature vector
    X = build_feature_vector(
        income_quartile, median_income, ownership,
        op18b_available, la_county, zip_code
    )

    # Run the model
    prediction = model.predict(X)[0]

    # ── Results ───────────────────────────────────────────────────────────────
    st.divider()
    st.subheader("Step 3 — Results")

    res1, res2, res3 = st.columns(3)

    res1.metric(
        label="Predicted Wait Time",
        value=f"{prediction:.0f} min",
        help="Linear Regression model prediction"
    )
    res2.metric(
        label="LA County Median",
        value="202 min",
        delta=f"{prediction - 202:.0f} min vs median",
        delta_color="inverse"
    )
    res3.metric(
        label="Model Uncertainty",
        value="± 44.73 min",
        help="Test RMSE of champion model"
    )

    # ── Category classification ───────────────────────────────────────────────
    st.markdown("**Wait Time Category** (based on LA County distribution):")

    LOW_THRESH  = 171  # 33rd percentile of LA County wait times
    HIGH_THRESH = 237  # 66th percentile of LA County wait times

    if prediction > HIGH_THRESH:
        st.error(
            f"🔴  **Higher Wait** — Predicted {prediction:.0f} min "
            f"exceeds the high-wait threshold of {HIGH_THRESH} min. "
            f"This facility falls in the top third of LA County wait times."
        )
    elif prediction > LOW_THRESH:
        st.warning(
            f"🟡  **Medium Wait** — Predicted {prediction:.0f} min "
            f"falls between {LOW_THRESH} and {HIGH_THRESH} min. "
            f"This facility is in the middle third of LA County wait times."
        )
    else:
        st.success(
            f"🟢  **Lower Wait** — Predicted {prediction:.0f} min "
            f"is below the low-wait threshold of {LOW_THRESH} min. "
            f"This facility is in the bottom third of LA County wait times."
        )

    # ── Feature contribution breakdown ───────────────────────────────────────
with st.expander("Feature values used for this prediction"):
    feature_summary = pd.DataFrame({
        "Feature":      ["Income Quartile", "Median Income",
                         "Ownership Type", "OP-18b Missing",
                         "LA County Match", "ZIP Code"],
        "Value":        [income_quartile, f"${median_income:,}",
                         ownership, "Yes" if op18b_available else "No",
                         "Yes" if la_county else "No", zip_code],
    })
    st.dataframe(feature_summary, use_container_width=True, hide_index=True)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    st.caption(
        "⚠  Disclaimer: This prediction carries ±44.73 min uncertainty "
        "(5-fold CV-RMSE = 55.81 ± 10.02 min). "
        "This tool is for research purposes only and should not be used "
        "for individual patient navigation decisions. "
        "Source: EquiCure Research Program, 2026."
    )
