# -*- coding: utf-8 -*-
"""3_Model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148g6XykV33t_YUl4qCQmhugP4lIqB8w-
"""

# pages/3_Model.py

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

from style import apply_global_style, page_header, sidebar_summary, COLOR

st.set_page_config(
    page_title="Model",
    page_icon="■",
    layout="wide",
)

apply_global_style()
sidebar_summary()

# Locate the main project folder.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Optional CSV containing all 14 model results.
MODEL_COMPARISON_PATH = (
    PROJECT_ROOT / "assets" / "model_comparison.csv"
)


page_header(
    "Model Performance",
    "Comparison of regression models for LA County emergency department wait-time prediction."
)

m1, m2, m3 = st.columns(3)
m1.metric("Models Tested", "14")
m2.metric("Champion", "Linear Regression")
m3.metric("CV-RMSE", "55.81 ± 10.02 min")

# ---------------------------------------------------------
# Cross-validation results
# ---------------------------------------------------------

st.subheader(
    "5-Fold Cross-Validation Results — Champion Model"
)

cv_df = pd.DataFrame(
    {
        "Fold": [
            "Fold 1",
            "Fold 2",
            "Fold 3",
            "Fold 4",
            "Fold 5",
        ],
        "RMSE": [
            45.34,
            64.88,
            67.15,
            58.97,
            42.71,
        ],
    }
)

mean_cv_rmse = cv_df["RMSE"].mean()
std_cv_rmse = cv_df["RMSE"].std(ddof=1)

fig_cv = px.bar(
    cv_df,
    x="Fold",
    y="RMSE",
    color_discrete_sequence=["#1565C0"],
    title=(
        f"CV-RMSE per Fold "
        f"(Mean = {mean_cv_rmse:.2f} ± "
        f"{std_cv_rmse:.2f} min)"
    ),
    text_auto=".2f",
)

fig_cv.add_hline(
    y=mean_cv_rmse,
    line_dash="dash",
    annotation_text=(
        f"Mean CV-RMSE = {mean_cv_rmse:.2f} min"
    ),
    annotation_position="top left",
)

fig_cv.update_layout(
    plot_bgcolor="white",
    yaxis_title="RMSE (minutes)",
)

st.plotly_chart(
    fig_cv,
    width="stretch",
)


# ---------------------------------------------------------
# Model comparison
# ---------------------------------------------------------

st.subheader("Model Comparison")

# Used only when assets/model_comparison.csv is unavailable.
fallback_models = pd.DataFrame(
    {
        "Model": [
            "Linear Regression",
            "SVR (RBF)",
            "Random Forest",
            "KNN (k=5)",
            "XGBoost",
            "LightGBM",
        ],
        "RMSE": [
            44.73,
            49.46,
            54.90,
            55.33,
            58.72,
            64.55,
        ],
    }
)


@st.cache_data
def load_model_results(
    file_path: Path,
) -> pd.DataFrame:
    """Load and validate the model-comparison table."""

    data = pd.read_csv(file_path)

    required_columns = {"Model", "RMSE"}
    missing_columns = (
        required_columns - set(data.columns)
    )

    if missing_columns:
        raise ValueError(
            "Missing required columns: "
            + ", ".join(sorted(missing_columns))
        )

    data["RMSE"] = pd.to_numeric(
        data["RMSE"],
        errors="coerce",
    )

    return data.dropna(
        subset=["Model", "RMSE"]
    )


if MODEL_COMPARISON_PATH.exists():
    try:
        model_df = load_model_results(
            MODEL_COMPARISON_PATH
        )

    except Exception as error:
        st.warning(
            f"Could not read "
            f"{MODEL_COMPARISON_PATH.name}: {error}. "
            "Showing the six supplied model results."
        )

        model_df = fallback_models.copy()

else:
    st.info(
        "Add `assets/model_comparison.csv` with at "
        "least `Model` and `RMSE` columns to display "
        "all 14 models. The six supplied results are "
        "shown below."
    )

    model_df = fallback_models.copy()


model_df = (
    model_df
    .sort_values("RMSE", ascending=True)
    .reset_index(drop=True)
)

model_df.insert(
    0,
    "Rank",
    range(1, len(model_df) + 1),
)

model_df["Champion"] = model_df["Rank"] == 1


fig_models = px.bar(
    model_df,
    x="Model",
    y="RMSE",
    color="Champion",
    color_discrete_map={
        True: "#2E7D32",
        False: "#1565C0",
    },
    title=(
        f"RMSE Comparison — "
        f"{len(model_df)} Models Shown"
    ),
    text_auto=".2f",
)

fig_models.update_layout(
    showlegend=False,
    plot_bgcolor="white",
    xaxis_tickangle=-35,
    yaxis_title="RMSE (minutes)",
)

st.plotly_chart(
    fig_models,
    width="stretch",
)


# Display all available result columns.
display_df = model_df.drop(
    columns="Champion"
)

st.dataframe(
    display_df,
    width="stretch",
    hide_index=True,
    column_config={
        "RMSE": st.column_config.NumberColumn(
            "RMSE",
            format="%.2f min",
        ),
    },
)


champion = model_df.iloc[0]

st.success(
    f"Champion: {champion['Model']} with "
    f"RMSE = {champion['RMSE']:.2f} min."
)
