# -*- coding: utf-8 -*-
"""4_Data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUQ2vvsTA3m3i10OrP0437_ayzpfAW98
"""

# pages/4_Data.py

import pandas as pd
import streamlit as st


st.set_page_config(
    page_title="Data",
    page_icon="■",
    layout="wide",
)


st.title("Data & Methods")
st.markdown(
    "5 public datasets · 58 LA County facilities · "
    "All data openly available"
)
st.divider()


# ---------------------------------------------------------
# Data sources
# ---------------------------------------------------------

st.subheader("Data Sources")

sources = pd.DataFrame(
    [
        {
            "Dataset": (
                "CMS Hospital General Information"
            ),
            "Source": "data.cms.gov",
            "What It Provides": (
                "Facility type, ownership, and location"
            ),
        },
        {
            "Dataset": (
                "CMS Timely & Effective Care (OP-18b)"
            ),
            "Source": "data.cms.gov",
            "What It Provides": (
                "ED wait time in minutes — "
                "primary outcome"
            ),
        },
        {
            "Dataset": (
                "HCAI ED Encounters by Facility"
            ),
            "Source": "data.chhs.ca.gov",
            "What It Provides": (
                "California facility-level ED volume"
            ),
        },
        {
            "Dataset": (
                "HCAI ED Characteristics "
                "(Pivot Profile)"
            ),
            "Source": "data.chhs.ca.gov",
            "What It Provides": (
                "Payer-mix data; attempted join "
                "was unsuccessful"
            ),
        },
        {
            "Dataset": (
                "U.S. Census ACS 5-Year Estimates"
            ),
            "Source": "census.gov",
            "What It Provides": (
                "Median household income by ZIP code"
            ),
        },
    ]
)

st.dataframe(
    sources,
    width="stretch",
    hide_index=True,
)


# ---------------------------------------------------------
# Limitations
# ---------------------------------------------------------

st.subheader("Known Limitations")

limitations = [
    (
        "Small Sample Size — 58 Facilities",
        (
            "The dataset is a complete census of "
            "LA County Medicare-certified emergency "
            "departments with valid OP-18b scores for "
            "the 2024–2025 reporting period. No "
            "additional rows met those constraints."
        ),
    ),
    (
        "Single Reporting Period",
        (
            "Only the 2024–2025 reporting period was "
            "used. Earlier years were excluded to "
            "reduce the risk of COVID-19-era conditions "
            "confounding the analysis."
        ),
    ),
    (
        "Payer-Mix Data Not Joinable",
        (
            "HCAI uses OSHPD identifiers, while CMS "
            "uses Provider IDs. A verified public "
            "crosswalk was not available for this "
            "analysis, so income quartile was retained "
            "as a socioeconomic proxy."
        ),
    ),
    (
        "Missing Operational Features",
        (
            "ED bed count, patient volume, staffing "
            "ratios, and other operational variables "
            "were not consistently available in the "
            "selected public datasets. Their absence "
            "may limit predictive performance."
        ),
    ),
]

for title, text in limitations:
    with st.expander(f"■ {title}"):
        st.write(text)


# ---------------------------------------------------------
# Analysis workflow
# ---------------------------------------------------------

st.subheader("Analysis Summary")

st.markdown(
    """
    1. Public facility, wait-time, encounter, and Census data were collected.
    2. Facility and ZIP-level fields were cleaned and standardized.
    3. Valid LA County facilities were retained after merging.
    4. Fourteen regression models were evaluated using RMSE and cross-validation.
    5. Subgroup error and SHAP analyses were used to examine disparities and model behavior.
    """
)