# -*- coding: utf-8 -*-
"""5_About.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105XCShXeX3liHyDI40eDZggB_MfnSRo1
"""

# pages/5_About.py

import streamlit as st

from style import apply_global_style, page_header, sidebar_summary, COLOR

st.set_page_config(
    page_title="About",
    page_icon="■",
    layout="wide",
)

apply_global_style()
sidebar_summary()

# Replace this with the final public repository URL.
# Example:
# GITHUB_URL = "https://github.com/username/repository"
GITHUB_URL = "https://github.com/AAAyuzhibo/Equi-Cure-Research"


page_header(
    "About EquiCure",
    "A student machine-learning research project focused on emergency care access and healthcare equity."
)


st.markdown(
    """
    ## The Program

    This research was conducted as part of the
    EquiCure + LabLink five-week machine-learning
    research program in Summer 2026. The program
    trains student researchers to apply machine
    learning to healthcare-equity questions using
    public datasets.

    ## Reproducibility

    The analysis uses five public datasets. The
    project code, data-processing steps, modeling
    workflow, and visualization scripts should be
    documented in the final GitHub repository so that
    the analysis can be independently reviewed and
    reproduced.
    """
)

st.subheader("The Team")

st.markdown(
    "The project was completed through four coordinated research roles covering data, modeling, equity analysis, and visualization."
)

col1, col2 = st.columns(2)

with col1:
    st.markdown(
        """
        <div class="info-card">
            <div class="info-card-title">R1 — Data Lead</div>
            <div class="info-card-name">Jiahao Liu</div>
            <div class="info-card-body">
                Data acquisition, cleaning, and merging. This role focused on preparing the public datasets and verifying that the analysis dataset was usable.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="info-card">
            <div class="info-card-title">R2 — Modeling Lead</div>
            <div class="info-card-name">Yulin Pan</div>
            <div class="info-card-body">
                Model evaluation, champion selection, and SHAP analysis. This role focused on testing machine learning models and interpreting prediction performance.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

with col2:
    st.markdown(
        """
        <div class="info-card">
            <div class="info-card-title">R3 — Equity Lead</div>
            <div class="info-card-name">Jianrong Zhu</div>
            <div class="info-card-body">
                Pre-registered equity analysis and findings brief. This role focused on subgroup performance and whether model error differed across equity-relevant groups.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="info-card">
            <div class="info-card-title">R4 — Visualization Lead</div>
            <div class="info-card-name">Yihong Zhu</div>
            <div class="info-card-body">
                Visualizations, Streamlit app, and launch deck. This role focused on communicating results through charts, the public-facing dashboard, and presentation materials.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------
# Project summary
# ---------------------------------------------------------

st.subheader("Project Scope")

left, middle, right = st.columns(3)

left.metric(
    "Facilities",
    "58",
)

middle.metric(
    "Models Evaluated",
    "14",
)

right.metric(
    "Primary Outcome",
    "ED wait time",
)


# ---------------------------------------------------------
# Repository link
# ---------------------------------------------------------

st.subheader("Repository")

if GITHUB_URL:
    st.link_button(
        "View GitHub Repository",
        GITHUB_URL,
        type="primary",
        width="stretch",
    )

else:
    st.info(
        "Add the final GitHub URL to `GITHUB_URL` "
        "near the top of `pages/5_About.py` to "
        "activate the repository button."
    )
