# -*- coding: utf-8 -*-
"""5_About.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105XCShXeX3liHyDI40eDZggB_MfnSRo1
"""

# pages/5_About.py

import streamlit as st


st.set_page_config(
    page_title="About",
    page_icon="■",
    layout="wide",
)


# Replace this with the final public repository URL.
# Example:
# GITHUB_URL = "https://github.com/username/repository"
GITHUB_URL = "https://github.com/AAAyuzhibo/Equi-Cure-Research"


st.title("About This Research")
st.markdown(
    "EquiCure + LabLink Summer 2026 Research Program"
)
st.divider()


st.markdown(
    """
    ## The Program

    This research was conducted as part of the
    EquiCure + LabLink five-week machine-learning
    research program in Summer 2026. The program
    trains student researchers to apply machine
    learning to healthcare-equity questions using
    public datasets.

    ## The Team

    | Role | Researcher | Responsibilities |
    |---|---|---|
    | R1 — Data Lead | Jiahao Liu | Data acquisition, cleaning, and merging |
    | R2 — Modeling Lead | Yulin Pan | Model evaluation, champion selection, and SHAP analysis |
    | R3 — Equity Lead | Jianrong Zhu | Pre-registered equity analysis and findings brief |
    | R4 — Visualization Lead | Yihong Zhu | Visualizations, Streamlit app, and launch deck |

    ## Reproducibility

    The analysis uses five public datasets. The
    project code, data-processing steps, modeling
    workflow, and visualization scripts should be
    documented in the final GitHub repository so that
    the analysis can be independently reviewed and
    reproduced.
    """
)


# ---------------------------------------------------------
# Project summary
# ---------------------------------------------------------

st.subheader("Project Scope")

left, middle, right = st.columns(3)

left.metric(
    "Facilities",
    "58",
)

middle.metric(
    "Models Evaluated",
    "14",
)

right.metric(
    "Primary Outcome",
    "ED wait time",
)


# ---------------------------------------------------------
# Repository link
# ---------------------------------------------------------

st.subheader("Repository")

if GITHUB_URL:
    st.link_button(
        "View GitHub Repository",
        GITHUB_URL,
        type="primary",
        width="stretch",
    )

else:
    st.info(
        "Add the final GitHub URL to `GITHUB_URL` "
        "near the top of `pages/5_About.py` to "
        "activate the repository button."
    )
